export const stock = {
  stock_item_id: "",
  name: "",
  category: "",
  description: "",
  quantity_in_stock: 0,
  minimum_quantity: 0,
  maximum_quantity: 0,
  reorder_level: 0,
  supplier: {
    supplier_id: "",
    name: "",
  },
  unit_price: 0,
  location: "",
  last_restock_date: "",
  next_restock_date: null,
  expiration_date: "",
  status: "",
  last_update: "",
};
